package:
    name: nnets
    version: "0.1"

source:
    git_rev: master
    git_url: https://github.com/Zaharid/nnets

requirements:
    build: 
        - python >=3.4
        - setuptools

    run:
        - python >=3.4
        - sympy
        - numba
        - numpy
        - scipy

about:
    home: https://github.com/Zaharid/nnets
    license: BSD
